apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "siglens.serviceAccountName" . }}
  labels:
    {{- include "siglens.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- if or .Values.k8sExporter.enabled .Values.logsExporter.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "siglens.serviceAccountName" . }}-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "siglens.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "siglens.serviceAccountName" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "siglens.serviceAccountName" . }}
{{ end }}