{{- if .Values.siglens.query.service.serviceType -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "siglens.fullname" . }}-query-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "siglens-server.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.siglens.query.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.siglens.query.service.serviceType }}
  ports:
    - port: {{ .Values.siglens.query.service.port }}
      targetPort: queryport
      protocol: TCP
      name: query-http
  selector:
    {{- include "siglens-server.selectorLabels" . | nindent 4 -}}
{{- end -}}