# Default values for siglens.
siglens:
  ingestReplicas: 1
  queryReplicas: 1
  image:
    repository: https://hub.docker.com/repository/docker/siglens/siglens
    pullPolicy: Always
    tag: 0.1.2
  ingest:
    resources: {}
    service:
      serviceType: "ClusterIP"
      port: 8081
      annotations: {}
    ingress:
      enabled: false
      annotations: {}
      class: ""
      host: ingest-example.local
      tls:
        enabled: false
        secretName: ""
  query:
    resources: {}
    service:
      serviceType: "ClusterIP"
      port: 8000
      annotations: {}
    ingress:
      enabled: false
      annotations: {}
      class: ""
      host: query-example.local
      tls:
        enabled: false
        secretName: ""

  # siglens configuration
  configs:
    ingestPort: 8081
    queryPort: 8000
    # queryHostname: "" # Set this to the DNS name of your siglens instance. i.e. set to the DNS name with no protocol or port
    # ingestUrl: "" # Set this to the full ingest URL of your siglens instance. i.e. set to the full URL with protocol and port
    # license:  ""
    # s3:
    #   enabled: false # if etcd is enabled, s3 is required
    #   bucketName: ""
    #   regionName: ""

  storage:
    # set to true for default class, else will create a new class with below arguments
    defaultClass: true

    # size of the volume the PVC will request
    size: 20Gi

    # Use EBS volume as default storage class
    # awsEBS:
    #   parameters: {}
    #
    # Create volume on a single node. The path must be present on the host
    # local:
    #   hostname: minikube
    #   capacity: 5Gi
    #   path: /data

# ETCD is used as a distributed key-value store for siglens horizontal scaling
etcd:
  enabled: false
  auth:
    rbac:
      create: false

k8sExporter:
  # Enable k8s events exporter to automatically ship events to siglens. If enabled, a cluster role will be created
  enabled: true
  image:
    repository: ghcr.io/opsgenie/kubernetes-event-exporter
    pullPolicy: IfNotPresent
    tag: v0.11
  configs:
    # output index name for kubernetes events
    index: kubernetes-events
  resources: {}
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
logsExporter:
  # Logs Exporter launches a fluentd daemonset that tails all container logs at /var/log/containers/*.log
  enabled: true
  image:
    repository: fluent/fluentd-kubernetes-daemonset
    pullPolicy: IfNotPresent
    tag: v1.14-debian-elasticsearch7-1
  resources: {}
  #   limits:
  #     cpu: 500m
  #     memory: 512Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}